[package]
name = "haesuk"
version = "0.1.0"
edition = "2021"

[dependencies]
strum = "0.26.3"
strum_macros = "0.26.4"
thiserror = "1.0"
lazy_static = "1.5.0"
# clap = { version = "4.5.16", features = ["derive"] }
